"""update messages table

Revision ID: be8a265f0303
Revises: 6821f6a210ab
Create Date: 2026-08-07 15:11:02.162216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8a265f0303'
down_revision = '6821f6a210ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('is_read')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
